const mongoose = require('mongoose');
// const Thismonth = require('./models/Thismonth'); 
const WomenFashion = require('./models/WomenFashion');

mongoose.connect('mongodb://localhost:27017/EcommorceSignup', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => {
    console.log('MongoDB connected');
    return WomenFashion.deleteMany(); // Optional: Clear existing data
  })
  .then(()=>{
    const WomenFashions =  [
      { name: 'Women Regular Fit Solid Spread Collar Casual Shirt', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/n/b/3/m-combo4898-901-funday-fashion-original-imagn5h2pweze7hz.jpeg?q=70', offerPrice:429, actualPrice:1499, discount: "33", rating: 4, discription: "Pack: 2, Style Code: Combo4898-901, Fit: Regular, Fabric: Crepe, Sleeve: Full Sleeve, Pattern: Solid, Reversible: No, Collar: Spread, Color: Pink, Black, Fabric Care: Hand wash, Suitable For: Western Wear, Net Quantity: 2", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Solid V Neck Cotton Blend Black T-Shirt', image: 'https://rukminim2.flixcart.com/image/612/612/kxnl6kw0/t-shirt/w/4/2/s-bi-women-v-neck-105-black-bi-fashion-original-imaga2d8sn286uqk.jpeg?q=70', offerPrice: 169, actualPrice:899, discount: "81", rating: 4.5, discription: "Elegant Pattern, Featuring a solid and elegant pattern this women's T-shirt effortlessly combines simplicity with style. The clean design makes it a versatile piece suitable for various occasions. Whether worn casually or dressed up with accessories this T-shirt is a wardrobe essential. The understated elegance of the solid colour enhances its versatility allowing you to pair it with jeans skirts or trousers for a polished look.  ", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Cotton Blend Kurta Pant Set', image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/n/8/p/l-meera-kangopi-fashion-original-imah3yaeevc28ymj.jpeg?q=70&crop=false', offerPrice: 369, actualPrice: 1499, discount: "75", rating: 4, discription:"Fabric: Cotton Blend, Type: Kurta and Pant Set, Sales Package: 1 Kurta with pant, Style Code: Meera, Secondary color: White, Top fabric: Cotton Blend, Bottom fabric: Cotton, Top type: Kurta, Bottom type: Pant, Pattern: Printed, Color: Pink, White, Occasion: Formal, Neck: Mandarin Collar, Fabric care: Normal Wash, Other Details: Cotton Kurta Pant Set, Look fabulous on any occasion with this kurti with pant set, It can be machine and hand washed", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Chanderi Kurta Pant Dupatta Set', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/0/x/a/s-rx44-ktd-rosegold-royal-export-original-imagyh5ufsmvv2yw.jpeg?q=70', offerPrice: 749, actualPrice:2099, discount: "64", rating: 4, discription: "Fabric: Chanderi, Type: Kurta, Pant And Dupatta Set, Sales Package: 1 KURTI, 1 PALAZZO, 1 DUPATTA, Style Code: CHANDERI, Secondary color: Purple, Lining material: chanderi, Top fabric: Art Silk, Bottom fabric: Silk, Top type: Kurta, Bottom type: Pant, Pattern: Embroidered, Color: Pink, Occasion: Festive & Party, Wedding, Neck: Round Neck, Fabric care: WASH IN COLD WATER", size: ['S', 'M', 'L', 'XL'] ,sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion"},
      { name: 'Casual Puff Sleeves Printed Women Black Top', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/top/k/l/1/-original-imah33d3gbtmnxp9.jpeg?q=70', offerPrice: 179, actualPrice:999, discount: "82", rating: 4, discription: "Neck: Sweetheart Neck, Sleeve Style: Puff Sleeves, Sleeve Length: Half Sleeve, Fit: Slim, Fabric: Polyester, Type: Regular Top, Belt Included: No, Pattern: Printed, Color: Black, Pack of: 1, Fabric Care: HandWash/MachineWash, Length: Hip Length, Style Code: Top-Modelo Black, Net Quantity: 1"      , size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women A-line Black, White, Brown Dress', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/dress/k/z/7/s-multi-dresses-fashion2wear-original-imah32jtnykmhdst.jpeg?q=70', offerPrice: 450, actualPrice:999, discount: "54", rating: 4, discription: "Color: Black, White, Brown, Length: Midi/Calf Length, Fabric: Georgette, Pattern: Floral Print, Ideal For: Women, Type: A-line, Style Code: Multi Dresses, Suitable For: Western Wear, Sleeve Length: 3/4 Sleeve, Pack of: 1, Neck: V-Neck, Fabric Care: Gentle Machine Wash, Sleeve: Regular Sleeves, Net Quantity: 1", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Regular Fit Solid Spread Collar Casual Shirt', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/n/b/3/m-combo4898-901-funday-fashion-original-imagn5h2pweze7hz.jpeg?q=70', offerPrice:429, actualPrice:1499, discount: "33", rating: 4, discription: "Pack: 2, Style Code: Combo4898-901, Fit: Regular, Fabric: Crepe, Sleeve: Full Sleeve, Pattern: Solid, Reversible: No, Collar: Spread, Color: Pink, Black, Fabric Care: Hand wash, Suitable For: Western Wear, Net Quantity: 2", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Solid V Neck Cotton Blend Black T-Shirt', image: 'https://rukminim2.flixcart.com/image/612/612/kxnl6kw0/t-shirt/w/4/2/s-bi-women-v-neck-105-black-bi-fashion-original-imaga2d8sn286uqk.jpeg?q=70', offerPrice: 169, actualPrice:899, discount: "81", rating: 4.5, discription: "Elegant Pattern, Featuring a solid and elegant pattern this women's T-shirt effortlessly combines simplicity with style. The clean design makes it a versatile piece suitable for various occasions. Whether worn casually or dressed up with accessories this T-shirt is a wardrobe essential. The understated elegance of the solid colour enhances its versatility allowing you to pair it with jeans skirts or trousers for a polished look.  ", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Cotton Blend Kurta Pant Set', image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/n/8/p/l-meera-kangopi-fashion-original-imah3yaeevc28ymj.jpeg?q=70&crop=false', offerPrice: 369, actualPrice: 1499, discount: "75", rating: 4, discription:"Fabric: Cotton Blend, Type: Kurta and Pant Set, Sales Package: 1 Kurta with pant, Style Code: Meera, Secondary color: White, Top fabric: Cotton Blend, Bottom fabric: Cotton, Top type: Kurta, Bottom type: Pant, Pattern: Printed, Color: Pink, White, Occasion: Formal, Neck: Mandarin Collar, Fabric care: Normal Wash, Other Details: Cotton Kurta Pant Set, Look fabulous on any occasion with this kurti with pant set, It can be machine and hand washed", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Chanderi Kurta Pant Dupatta Set', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/0/x/a/s-rx44-ktd-rosegold-royal-export-original-imagyh5ufsmvv2yw.jpeg?q=70', offerPrice: 749, actualPrice:2099, discount: "64", rating: 4, discription: "Fabric: Chanderi, Type: Kurta, Pant And Dupatta Set, Sales Package: 1 KURTI, 1 PALAZZO, 1 DUPATTA, Style Code: CHANDERI, Secondary color: Purple, Lining material: chanderi, Top fabric: Art Silk, Bottom fabric: Silk, Top type: Kurta, Bottom type: Pant, Pattern: Embroidered, Color: Pink, Occasion: Festive & Party, Wedding, Neck: Round Neck, Fabric care: WASH IN COLD WATER", size: ['S', 'M', 'L', 'XL'] ,sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion"},
      { name: 'Women Solid V Neck Cotton Blend Black T-Shirt', image: 'https://rukminim2.flixcart.com/image/612/612/kxnl6kw0/t-shirt/w/4/2/s-bi-women-v-neck-105-black-bi-fashion-original-imaga2d8sn286uqk.jpeg?q=70', offerPrice: 169, actualPrice:899, discount: "81", rating: 4.5, discription: "Elegant Pattern, Featuring a solid and elegant pattern this women's T-shirt effortlessly combines simplicity with style. The clean design makes it a versatile piece suitable for various occasions. Whether worn casually or dressed up with accessories this T-shirt is a wardrobe essential. The understated elegance of the solid colour enhances its versatility allowing you to pair it with jeans skirts or trousers for a polished look.  ", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Cotton Blend Kurta Pant Set', image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/n/8/p/l-meera-kangopi-fashion-original-imah3yaeevc28ymj.jpeg?q=70&crop=false', offerPrice: 369, actualPrice: 1499, discount: "75", rating: 4, discription:"Fabric: Cotton Blend, Type: Kurta and Pant Set, Sales Package: 1 Kurta with pant, Style Code: Meera, Secondary color: White, Top fabric: Cotton Blend, Bottom fabric: Cotton, Top type: Kurta, Bottom type: Pant, Pattern: Printed, Color: Pink, White, Occasion: Formal, Neck: Mandarin Collar, Fabric care: Normal Wash, Other Details: Cotton Kurta Pant Set, Look fabulous on any occasion with this kurti with pant set, It can be machine and hand washed", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women Chanderi Kurta Pant Dupatta Set', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/0/x/a/s-rx44-ktd-rosegold-royal-export-original-imagyh5ufsmvv2yw.jpeg?q=70', offerPrice: 749, actualPrice:2099, discount: "64", rating: 4, discription: "Fabric: Chanderi, Type: Kurta, Pant And Dupatta Set, Sales Package: 1 KURTI, 1 PALAZZO, 1 DUPATTA, Style Code: CHANDERI, Secondary color: Purple, Lining material: chanderi, Top fabric: Art Silk, Bottom fabric: Silk, Top type: Kurta, Bottom type: Pant, Pattern: Embroidered, Color: Pink, Occasion: Festive & Party, Wedding, Neck: Round Neck, Fabric care: WASH IN COLD WATER", size: ['S', 'M', 'L', 'XL'] ,sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion"},
      { name: 'Casual Puff Sleeves Printed Women Black Top', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/top/k/l/1/-original-imah33d3gbtmnxp9.jpeg?q=70', offerPrice: 179, actualPrice:999, discount: "82", rating: 4, discription: "Neck: Sweetheart Neck, Sleeve Style: Puff Sleeves, Sleeve Length: Half Sleeve, Fit: Slim, Fabric: Polyester, Type: Regular Top, Belt Included: No, Pattern: Printed, Color: Black, Pack of: 1, Fabric Care: HandWash/MachineWash, Length: Hip Length, Style Code: Top-Modelo Black, Net Quantity: 1"      , size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" },
      { name: 'Women A-line Black, White, Brown Dress', image: 'https://rukminim2.flixcart.com/image/612/612/xif0q/dress/k/z/7/s-multi-dresses-fashion2wear-original-imah32jtnykmhdst.jpeg?q=70', offerPrice: 450, actualPrice:999, discount: "54", rating: 4, discription: "Color: Black, White, Brown, Length: Midi/Calf Length, Fabric: Georgette, Pattern: Floral Print, Ideal For: Women, Type: A-line, Style Code: Multi Dresses, Suitable For: Western Wear, Sleeve Length: 3/4 Sleeve, Pack of: 1, Neck: V-Neck, Fabric Care: Gentle Machine Wash, Sleeve: Regular Sleeves, Net Quantity: 1", size: ['S', 'M', 'L', 'XL'],sideimg1:"https://rukminim2.flixcart.com/image/832/832/xif0q/watch/l/m/e/-original-imagz4hkqpmhh6gd.jpeg?q=70&crop=false", sideimg2:"https://rukminim2.flixcart.com/image/128/128/xif0q/watch/l/c/z/-original-imaghny5zgcpvwet.jpeg?q=70&crop=false", sideimg3:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/7/q/a/ls2978-limestone-original-imagf8assmvzdshh.jpeg?q=70&crop=false", sideimg4:"https://rukminim2.flixcart.com/image/128/128/kmax8y80/watch/l/a/m/ls2978-limestone-original-imagf8ascyfpkr9j.jpeg?q=70&crop=false",type:"WomenFashion" }
    ];

      return WomenFashion.insertMany(WomenFashions)
  
  })
  .then(() => {
    console.log('Products inserted');
    mongoose.connection.close();
  })
  .catch(err => {
    console.error(err);
    mongoose.connection.close();
  });